language: cpp
compiler: g++-9
os: linux
dist: focal
env: CXX=g++-9

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-9
            - libssl-dev

script:
    - make
    - sudo make install
    - ./cp-tools -v
    - ./cp-run_tests

after_success:
    - echo "Success"

after_failure:
    - echo "Failure"
