language: cpp
compiler: g++-8
os: linux
env: CXX=g++-8

addons:
    apt:
        update: true
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8

before_install:
    - sudo apt-get -y install libssl-dev

script:
    - make
    - sudo make install
    - ./cp-tools -v
    - ./cp-run_tests

after_sucess:
    - echo "Success"

after_failure:
    - echo "Failure"
